call pook.off in the end of pook.activate wrapper function
h2non/pook pull request #145
Opened 2024-10-14 04:44 UTC by shift0965

This PL is for this [issue](https://github.com/h2non/pook/issues/144)

2024-10-14 19:57 UTC, sarayourfriend commented
Thank you for the issue and PR @shift0965 :pray: Can you add a unit test for this fix? You will also need to update `activate_async` to fix the same problem for async tests: https://github.com/h2non/pook/blob/master/src/pook/activate_async.py#L26

We'll need a unit test for each as well. If you would like guidance on adding the tests, let me know and I can give some pointers.

2024-10-14 20:52 UTC, sarayourfriend requested changes
Thank you for the issue and PR @shift0965 :pray: Can you add a unit test for this fix? You will also need to update `activate_async` to fix the same problem for async tests: https://github.com/h2non/pook/blob/master/src/pook/activate_async.py#L26

We'll need a unit test for each as well. If you would like guidance on adding the tests, let me know and I can give some pointers.

2024-10-15 02:17 UTC, shift0965 commented
Thank you for you feedback! I just added test cases for each scenario and let me know if there are any further adjustments you like me to make.

2024-10-15 02:18 UTC, sarayourfriend approved these changes
LGTM! One small change needed to get the tests to run (the test function needs to be async), but I'll commit that for you and then CI should pass and I can merge and release today :slightly_smiling_face: 

Thanks again for the contribution :tada:

2024-10-15 02:18 UTC, sarayourfriend commented on tests/unit/api_test.py
> +def test_activate_as_decorator_for_async(engine):
```suggestion
async def test_activate_as_decorator_for_async(engine):
```

2024-10-15 02:21 UTC, sarayourfriend commented on tests/unit/api_test.py
> +
```suggestion
```

2024-10-15 02:21 UTC, sarayourfriend commented on tests/unit/api_test.py
> +
```suggestion
```

2024-10-15 02:34 UTC, merged